CREATE TABLE IF NOT EXISTS "token_deploy" (
	"transaction_hash" text PRIMARY KEY NOT NULL,
	"network" text,
	"block_hash" text,
	"block_number" bigint,
	"block_timestamp" timestamp,
	"memecoin_address" text,
	"owner_address" text,
	"name" text,
	"symbol" text,
	"initial_supply" text,
	"total_supply" text,
	"_cursor" bigint,
	"time_stamp" timestamp,
	"created_at" timestamp DEFAULT now(),
	"is_launched" boolean,
	"description" text,
	"ipfs_hash" text,
	"ipfs_metadata_url" text,
	"nostr_id" text,
	"url" text,
	"github" text,
	"image_url" text,
	"metadata" json,
	"nostr_event_id" text,
	"telegram" text,
	"twitter" text,
	"website" text,
	CONSTRAINT "token_deploy_memecoin_address_unique" UNIQUE("memecoin_address")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "token_launch" (
	"transaction_hash" text PRIMARY KEY NOT NULL,
	"network" text,
	"block_hash" text,
	"owner_address" text,
	"block_number" bigint,
	"block_timestamp" timestamp,
	"memecoin_address" text,
	"quote_token" text,
	"exchange_name" text,
	"total_supply" text,
	"threshold_liquidity" text,
	"current_supply" text,
	"liquidity_raised" text,
	"is_liquidity_added" boolean,
	"total_token_holded" text,
	"price" text,
	"bonding_type" text,
	"_cursor" bigint,
	"time_stamp" timestamp,
	"created_at" timestamp DEFAULT now(),
	"initial_pool_supply_dex" text,
	"market_cap" text,
	"description" text,
	"github" text,
	"image_url" text,
	"ipfs_hash" text,
	"ipfs_metadata_url" text,
	"metadata" json,
	"nostr_event_id" text,
	"nostr_id" text,
	"telegram" text,
	"twitter" text,
	"url" text,
	"website" text,
	"name" text,
	"symbol" text,
	"token_deploy_tx_hash" text,
	CONSTRAINT "token_launch_memecoin_address_unique" UNIQUE("memecoin_address"),
	CONSTRAINT "token_launch_token_deploy_tx_hash_unique" UNIQUE("token_deploy_tx_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "token_metadata" (
	"transaction_hash" text PRIMARY KEY NOT NULL,
	"network" text,
	"block_hash" text,
	"block_number" bigint,
	"contract_address" text,
	"block_timestamp" timestamp,
	"memecoin_address" text,
	"url" text,
	"nostr_id" text,
	"name" text,
	"symbol" text,
	"_cursor" bigint,
	"time_stamp" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"nostr_event_id" text,
	CONSTRAINT "token_metadata_memecoin_address_unique" UNIQUE("memecoin_address")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "token_transactions" (
	"transfer_id" text PRIMARY KEY NOT NULL,
	"network" text,
	"block_hash" text,
	"block_number" bigint,
	"block_timestamp" timestamp,
	"transaction_hash" text,
	"memecoin_address" text,
	"owner_address" text,
	"last_price" text,
	"quote_amount" text,
	"coin_received" text,
	"initial_supply" text,
	"created_at" timestamp DEFAULT now(),
	"total_supply" text,
	"current_supply" text,
	"liquidity_raised" text,
	"price" text,
	"protocol_fee" text,
	"amount" numeric(30, 18),
	"_cursor" bigint,
	"transaction_type" text,
	"time_stamp" timestamp
);
