FROM quay.io/apibara/sink-webhook:0.6.0

WORKDIR /indexer
COPY ./backend/indexer/script.js /indexer

ENTRYPOINT ["/nix/store/2l9p053ypiyh4i1r0b82ml4f1x0fy0sp-apibara-sink-webhook-0.6.0/bin/apibara-sink-webhook"]