FROM --platform=linux/amd64 golang:1.22.2-alpine

RUN apk add --no-cache bash curl git jq

# Copy over the configs
COPY ./configs/docker-backend.config.json ./backend.config.json

# Copy over the app
WORKDIR /app
COPY /go.mod /go.sum ./
RUN go mod download
COPY ./ .

RUN go build -o main ./cmd/backend/backend.go

EXPOSE 8080

CMD ["./main"]