[profile.default]
src = "solidity_contracts/src"
test = "solidity_contracts/test"
out = "out"
libs = ["solidity_contracts/lib", "lib/kakarot-rpc"]
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
