[package]
name = "afk"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.8.2"
# openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag="v0.13.0" }
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag="v0.18.0" }


[dev-dependencies]
# snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.25.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.32.0" }

#[lib]

[scripts]
test = "snforge test"

[tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
casm = true
sierra = true
allowed-libfuncs-list.name = "experimental"
