version: "3"

services:
  devnet:
    image: shardlabs/starknet-devnet-rs:0.0.3
    command:
      - --dump-on=transaction
      - --dump-path=/data/dump
      - --seed=42
    volumes:
      - devnet:/data
    ports:
      - 5050:5050

  dna:
    image: quay.io/apibara/starknet:1.5.0
    command:
      - start
      - --rpc=http://devnet:5050/rpc
      - --name=devnet
      - --head-refresh-interval-ms=1000
      - --wait-for-rpc
      - --address=0.0.0.0:7171
    environment:
      - XDG_DATA_HOME=/data
    volumes:
      - dna:/data
    ports:
      - 7171:7171
    depends_on:
      devnet:
        condition: service_started

volumes:
  devnet:
  dna:
