import {Platform} from 'react-native';

import {ThemedStyleSheet} from '../../styles';

export default ThemedStyleSheet((theme) => ({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    padding: 16,
    flexGrow: 1,
  },
  headerText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: theme.colors.streamStudio_text,
    marginBottom: 16,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 100,
  },
  emptyStateText: {
    fontSize: 18,
    color: theme.colors.streamStudio_textSecondary,
    marginTop: 16,
    marginBottom: 24,
  },
  hashTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  eventCard: {
    borderWidth: 1,
    borderColor: theme.colors.streamStudio_inputBorder,
    backgroundColor: theme.colors.streamStudio_cardBackground,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    ...Platform.select({
      ios: {
        shadowColor: theme.colors.shadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  eventTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.streamStudio_text,
    flex: 1,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.streamStudio_buttonText,
  },
  eventDescription: {
    fontSize: 14,
    color: theme.colors.streamStudio_textSecondary,
    marginBottom: 8,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  dateText: {
    marginLeft: 8,
    fontSize: 14,
    color: theme.colors.streamStudio_text,
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  tag: {
    backgroundColor: theme.colors.streamStudio_tagBackground,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    fontSize: 12,
    color: theme.colors.streamStudio_tagText,
  },
  picker: {
    height: 40,
    borderRadius: 8,
    padding: 5,
    borderColor: theme.colors.streamStudio_inputBorder,
    borderWidth: 1,
    backgroundColor: theme.colors.streamStudio_inputBackground,
    color: theme.colors.streamStudio_inputText,
  },
  viewButton: {
    borderWidth: 1,
    flex: 1,
    borderColor: theme.colors.streamStudio_inputBorder,
    backgroundColor: theme.colors.streamStudio_cardBackground,
    borderRadius: 8,
    justifyContent: 'center',
    fontSize: 12,
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    padding: 10,
    gap: 6,
  },
  viewButtonText: {
    fontSize: 12,
    fontWeight: 'medium',
    color: theme.colors.streamStudio_buttonText,
  },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.streamStudio_buttonBackground,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  createButtonText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.streamStudio_buttonText,
  },
  floatingCreateButton: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    backgroundColor: theme.colors.streamStudio_buttonBackground,
    borderRadius: 30,
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: theme.colors.shadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.3,
        shadowRadius: 4,
      },
      android: {
        elevation: 5,
      },
    }),
  },
  label: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 10,
  },
  selectedDates: {
    marginTop: 20,
    alignItems: 'center',
  },
  selectedDateText: {
    fontSize: 16,
    marginBottom: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    margin: 'auto',
    width: '100%',
    borderWidth: 1,
    borderColor: theme.colors.streamStudio_inputBorder,
    maxWidth: 500,
    backgroundColor: theme.colors.streamStudio_surface,
    borderRadius: 20,
    padding: 35,
    alignItems: 'stretch',
    ...Platform.select({
      ios: {
        shadowColor: theme.colors.shadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.25,
        shadowRadius: 4,
      },
      android: {
        elevation: 5,
      },
    }),
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.streamStudio_text,
    marginBottom: 25,
  },
  input: {
    backgroundColor: theme.colors.streamStudio_inputBackground,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    color: theme.colors.inputText,
    borderWidth: 1,
    borderColor: theme.colors.streamStudio_inputBorder,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  dateLabel: {
    fontSize: 12,
    color: theme.colors.inputPlaceholder,
    marginBottom: 4,
  },
  modalButton: {
    backgroundColor: theme.colors.streamStudio_buttonBackground,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.streamStudio_buttonText,
  },
  cancelButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: theme.colors.streamStudio_buttonBackground,
  },
}));
