import {Spacing, ThemedStyleSheet} from '../../styles';

export default ThemedStyleSheet((theme) => ({
  chatContainer: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: '50%',
    minWidth: 280,
    // backgroundColor: theme.colors.surface,
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.divider,
  },
  chatHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.divider,
  },
  chatTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
  },
  actionButtonText: {
    color: theme.colors.text,
  },
  chatMessages: {
    paddingHorizontal: 10,
    paddingBottom: 10,
    marginTop: 'auto',
  },
  messageContainer: {
    flexDirection: 'row',
    color: theme.colors.messageCardText,
    backgroundColor: theme.colors.messageCard,
    padding: 10,
    borderRadius: 10,
    marginVertical: 5,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  avatarText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  messageContent: {
    flex: 1,
  },
  messageSender: {
    fontWeight: 'bold',
    marginBottom: 4,
    color: theme.colors.messageCardText,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.messageCardText,
  },
  chatInputContainer: {
    flexDirection: 'row',
    padding: 8,
    borderTopWidth: 1,
    borderTopColor: theme.colors.divider,
    backgroundColor: theme.colors.surface,
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.colors.divider,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 8,
    color: theme.colors.text,
  },
  sendButton: {
    backgroundColor: theme.colors.secondary,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  sendButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  replyIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.messageCard,
    padding: Spacing.small,
    borderRadius: Spacing.xsmall,
    marginBottom: Spacing.small,
    borderWidth: 1,
    borderColor: theme.colors.text,
    margin: Spacing.small,
  },
  replyContent: {
    flex: 1,
  },
  replyText: {
    fontSize: 14,
    color: theme.colors.text,
  },
  cancelButton: {
    marginLeft: Spacing.small,
    padding: Spacing.xsmall,
  },
  cancelButtonText: {
    fontSize: 16,
    color: theme.colors.text,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuContainer: {
    backgroundColor: theme.colors.background,
    borderWidth: 1,
    borderColor: theme.colors.text,
    borderRadius: Spacing.xsmall,
    padding: Spacing.small,
    minWidth: '70%',
  },
  menuItem: {
    paddingVertical: 8,
  },
  menuItemText: {
    fontSize: 16,
    color: theme.colors.text,
  },
  replyContainer: {
    backgroundColor: theme.colors.messageReplyCard,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: theme.colors.divider,
    padding: 10,
    marginVertical: 5,
    borderLeftColor: theme.colors.blue,
    borderLeftWidth: 3,
  },
  replySender: {
    fontWeight: 'bold',
    fontSize: 12,
    color: theme.colors.messageReplyCardText,
    marginBottom: 2,
  },
  // chatContainer: {
  //   position: 'absolute',
  //   right: 0,
  //   top: 0,
  //   bottom: 0,
  //   width: '50%',
  //   minWidth: 280,
  //   backgroundColor: theme.colors.surface,
  //   borderLeftWidth: 1,
  //   borderLeftColor: theme.colors.divider,
  // },
  // chatHeader: {
  //   flexDirection: 'row',
  //   justifyContent: 'space-between',
  //   alignItems: 'center',
  //   padding: 16,
  //   borderBottomWidth: 1,
  //   borderBottomColor: theme.colors.divider,
  // },
  // chatTitle: {
  //   fontSize: 18,
  //   fontWeight: '600',
  //   color: theme.colors.text,
  // },
  // chatMessages: {
  //   flex: 1,
  //   padding: 16,
  // },
  // messageContainer: {
  //   flexDirection: 'row',
  //   marginBottom: 16,
  // },
  // avatar: {
  //   width: 32,
  //   height: 32,
  //   borderRadius: 16,
  //   backgroundColor: theme.colors.primary,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   marginRight: 8,
  // },
  // avatarText: {
  //   color: theme.colors.onPrimary,
  //   fontSize: 16,
  //   fontWeight: '600',
  // },
  // messageContent: {
  //   flex: 1,
  //   backgroundColor: theme.colors.messageCard,
  //   padding: 12,
  //   borderRadius: 12,
  // },
  // messageSender: {
  //   fontSize: 14,
  //   fontWeight: '600',
  //   color: theme.colors.messageCardText,
  //   marginBottom: 4,
  // },
  // messageText: {
  //   fontSize: 14,
  //   color: theme.colors.textSecondary,
  // },
  // chatInputContainer: {
  //   flexDirection: 'row',
  //   padding: 16,
  //   borderTopWidth: 1,
  //   borderTopColor: theme.colors.divider,
  //   marginBottom: 'auto',
  // },
  // chatInput: {
  //   flex: 1,
  //   backgroundColor: theme.colors.inputBackground,
  //   borderRadius: 20,
  //   paddingHorizontal: 16,
  //   paddingVertical: 8,
  //   marginRight: 8,
  //   fontSize: 14,
  //   color: theme.colors.inputText,
  // },
  // sendButton: {
  //   backgroundColor: theme.colors.primary,
  //   paddingHorizontal: 16,
  //   paddingVertical: 8,
  //   borderRadius: 20,
  //   justifyContent: 'center',
  // },
  // sendButtonText: {
  //   color: theme.colors.onPrimary,
  //   fontWeight: '600',
  // },

  // actionButtonText: {
  //   color: theme.colors.text,
  // },

  //Share button
  share_button: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  share_icon: {
    marginRight: 8,
  },
  share_buttonText: {
    color: 'white',
    fontSize: 13,
    fontWeight: 'bold',
  },
}));
