export const TAGS_DEFAULT= [
    "bitcoin",
    "nostr",
    "freedom",
    "privacy",
    "economics",
    "finance",
    "spirituality",
    "psychology",
    "geopolitics",
    "politics",
    "education",
    "technology",
    "science",
    "philosophy",
    "history",
    "culture",
    "literature",
    "music",
    "p2p",
    "cashu",
    "lightning network",
    "memes",
    "art",
    "zk",
    "cryptography",
    "ai",
    "dev",
 
    // "zero-knowledge-proof",
    // "zkp",
    "math",

    "crypto",
    "ordinals",
    "runes",
    "music",
    "blockchain",
    "web3",
    "defi",
    "nft",
    
    
]