name: CI

on:
  push:
    branches:
      - main
    paths:
      - "apps/mobile/**"
  pull_request:
    branches:
      - main
    paths:
      - "apps/mobile/**"

jobs:
  check-app:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/mobile

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Prettier Format Check
        run: pnpm format:check

      - name: ESLint Check
        run: pnpm lint

      - name: TypeScript Check
        run: pnpm ts:check
