name: Starknet Contracts

on:
  push:
    paths:
      - "onchain/cairo/**"
  pull_request:
    branches:
      - main
    paths:
      - "onchain/cairo/**"

permissions: read-all

jobs:
  afk-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: onchain/cairo/afk/.tool-versions
          scarb-lock: onchain/cairo/afk/scarb.lock
      - name: Check cairo format
        run: scarb fmt --check
        working-directory: onchain/cairo/afk
      - name: Build cairo programs
        run: scarb build
        working-directory: onchain/cairo/afk
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: onchain/cairo/afk/.tool-versions
      - name: Run cairo tests
        run: snforge test
        working-directory: onchain/cairo/afk
  launchpad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: onchain/cairo/launchpad/.tool-versions
          scarb-lock: onchain/cairo/launchpad/scarb.lock
      - name: Check cairo format
        run: scarb fmt --check
        working-directory: onchain/cairo/launchpad
      - name: Build cairo programs
        run: scarb build
        working-directory: onchain/cairo/launchpad
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          tool-versions: onchain/cairo/launchpad/.tool-versions
      - name: Run cairo tests
        run: snforge test
        working-directory: onchain/cairo/launchpad
